version: "3.1"
services:
   wvww:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/opt/wvww
    networks:
      - wvww
      - nginx-load-balancer
    ports:
      - "5000:5000"
    restart: always
networks:
  wvww:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
