"""add max messages

Revision ID: 225a46d6c3f5
Revises: c0f739474b30
Create Date: 2020-04-15 17:34:49.076383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225a46d6c3f5'
down_revision = 'c0f739474b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sents_date', table_name='sents')
    op.add_column('words', sa.Column('max_texts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'max_texts')
    op.create_index('ix_sents_date', 'sents', ['date'], unique=False)
    # ### end Alembic commands ###
