"""words table

Revision ID: 39e5f8fdc0cf
Revises: 574553fee9fd
Create Date: 2020-04-10 17:09:49.464197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e5f8fdc0cf'
down_revision = '574553fee9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corpus_words', sa.String(length=200), nullable=True),
    sa.Column('topic_words', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    # ### end Alembic commands ###
