"""posts table

Revision ID: 574553fee9fd
Revises: c33a80e4698d
Create Date: 2020-04-10 14:00:13.761908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574553fee9fd'
down_revision = 'c33a80e4698d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.String(length=5), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
