"""adding sents

Revision ID: 78145fe6e3c7
Revises: 2aa9eb1b2044
Create Date: 2020-04-14 09:51:44.875758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78145fe6e3c7'
down_revision = '2aa9eb1b2044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corpus', sa.String(length=200), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('parties', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('entity', sa.String(length=200), nullable=True),
    sa.Column('polarity', sa.String(length=200), nullable=True),
    sa.Column('objectivity', sa.String(length=200), nullable=True),
    sa.Column('direct_words', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sents')
    # ### end Alembic commands ###
