"""words table

Revision ID: 8a2ccda51ebb
Revises: 39e5f8fdc0cf
Create Date: 2020-04-10 17:32:26.863713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2ccda51ebb'
down_revision = '39e5f8fdc0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('corpus_words_raw', sa.String(length=200), nullable=True))
    op.add_column('words', sa.Column('topic_words_raw', sa.String(length=200), nullable=True))
    op.drop_column('words', 'topic_words')
    op.drop_column('words', 'corpus_words')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('corpus_words', sa.VARCHAR(length=200), nullable=True))
    op.add_column('words', sa.Column('topic_words', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('words', 'topic_words_raw')
    op.drop_column('words', 'corpus_words_raw')
    # ### end Alembic commands ###
